apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-driven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-driven-app
  template:
    metadata:
      labels:
        app: event-driven-app
    spec:
      serviceAccountName: kubernetes-sa
      containers:
        - name: event-driven-app
          image: gcr.io/gcp-k8s-event-driven-app/event-driven-app:latest
          env:
            - name: PROJECT_ID
              value: "gcp-k8s-event-driven-app"
            - name: SUBSCRIPTION_ID
              value: "my-subscription"
            - name: BUCKET_NAME
              value: "b234cke5678t"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/service-account-key/gcp-k8s-event-driven-app-092926fb4459.json  # Path to your service account key
          volumeMounts:
            - name: service-account-key
              mountPath: /etc/service-account-key  # This is where the key will be accessible in the container
      volumes:
        - name: service-account-key
          secret:
            secretName: service-account-key  # Reference to the secret you created
