apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-driven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-driven-app
  template:
    metadata:
      labels:
        app: event-driven-app
    spec:
      containers:
      - name: event-driven-app
        image: gcr.io/gcp-k8s-event-driven-app/event-driven-app:latest
        env:
        - name: PROJECT_ID
          value: "gcp-k8s-event-driven-app"  # Your GCP project ID
        - name: SUBSCRIPTION_ID
          value: "my-subscription"  # Your Pub/Sub subscription ID
        - name: BUCKET_NAME
          value: "b234cke5678t"  # Your Cloud Storage bucket name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/gcp/gcp-k8s-event-driven-app-bd44f4a65fc2.json"  # Updated to match the secret file name
        volumeMounts:
        - name: gcp-credentials
          mountPath: /secrets/gcp  # Mount secret at this path
          readOnly: true
      volumes:
      - name: gcp-credentials
        secret:
          secretName: service-account-key  # Name of the secret created in Kubernetes

