apiVersion: v1
kind: Service
metadata:
  name: event-driven-app
spec:
  selector:
    app: event-driven-app
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 8080  # Port your app is running on
  type: LoadBalancer   # Use NodePort if you're on a local cluster
